// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "NativeGameplayTags.h"

namespace EQGameplayTag
{
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Notify_ButtonPressed);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_State_Jumping);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_State_ToggleCombat);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_State_ToggleCooldown);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_State_Combat);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_State_Attacking);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_State_Skilling);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_State_SkillCooldown);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_State_Rolling);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_State_Sprinting);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_State_Hit);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_State_Invincible);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_State_Blocking);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_State_Parrying);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_State_Parried);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_State_Stunned);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_State_DrinkingPotion);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_State_Dead);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_Action_Equip);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_Action_Unequip);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_Action_AttackHitCheck);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_Action_SkillHitCheck);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_Action_HitReaction);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_Action_BlockingHit);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_Action_ParriedHit);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_Action_KnockBackHit);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_Attack_Light);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_Attack_Running);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_Attack_Special);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_Attack_Heavy);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_Attack_Air);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_Data_Damage);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Character_AttackHit);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Character_Damage);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Character_NotEnoughStamina);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_WarningPrompt_Show);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_WarningPrompt_Hide);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_InteractPrompt_Show);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_InteractPrompt_Hide);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_ItemBox_Open);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_PickupItem_Spawn);
}
